version: '3.7'

networks:
  711-network:
    external: true

volumes:
  mysql-data:

services:
  test:
    container_name: build_test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 81:80

  app:
    container_name: 711-community
    image: harbor.ha-ving.store/docker/711-community:latest
    ports:
      - 8282:80

  mysql:
    image: bitnami/mysql:8.3
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mysql-data:/opt/bitnami/mysql