version: '3.7'

networks:
  711-network:
    external: true

volumes:
  mysql-data:

services:
  mysql:
    image: bitnami/mysql:8.3
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mysql-data:/opt/bitnami/mysql