domain:
    name: http://${711_DOMAIN}:${711_BACKEND_PORT}
server:
    port: ${711_BACKEND_PORT}
    forward-headers-strategy: FRAMEWORK


spring:
    docker:
        compose:
            lifecycle-management: start-and-stop
            start:
                command: up
            stop:
                command: down
                timeout: 1m

    datasource:
        url: jdbc:h2:mem:local;MODE=MySQL;DATABASE_TO_LOWER=TRUE #mysql ?? ??
        username: fast
        password: ${711_DATABASE_PASSWORD}
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            ddl-auto: update
            format_sql: true
            show_sql: true

## docs
springdoc:
    default-produces-media-type: application/json;charset=UTF-8
    default-consumes-media-type: application/json;charset=UTF-8
    swagger-ui:
        path: /api-docs.html
        operations-sorter: method
#        disable-swagger-default-url: true
        display-request-duration: true

    api-docs:
        path: /api-docs

## log
logging:
    level:
        org:
            springframework:
                security: INFO
---

