server:
  port: 8181

spring:
    sql:
      init:
        mode: always
    jpa:
      defer-datasource-initialization: true
      hibernate:
        ddl-auto: create-drop

      properties:
        hibernate:
          format_sql: true
          show_sql: true

logging:
  level:
    com.aptner.v3: debug
    org.hibernate.SQL: error