server:
  port: 8181

spring:
    datasource:
      url: jdbc:mysql://${711_DOMAIN}:3306/${711_DATABASE}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: fast
      password: ${711_DATABASE_PASSWORD}

    jpa:
      hibernate:
        ddl-auto: create-drop

logging:
  level:
    com.aptner.v3: debug