server:
    port: 80
    forward-headers-strategy: FRAMEWORK

spring:
    profiles:
        include: hidden
    h2:
        console:
            enabled: true
            path: /h2-console
    sql:
        init:
            mode: always

    jpa:
        defer-datasource-initialization: true
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            ddl-auto: create-drop


## docs
springdoc:
    default-produces-media-type: application/json;charset=UTF-8
    default-consumes-media-type: application/json;charset=UTF-8
    swagger-ui:
        path: /api-docs.html
        operations-sorter: method
#        disable-swagger-default-url: true
        display-request-duration: true

    api-docs:
        path: /api-docs
---