name: Docker Build 🚀

on:
  push:
    branches: [ "feature*", "master" ]
  workflow_dispatch:

jobs:
  gradle:
    name: Gradle Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: SPRING_PROFILES_ACTIVE=dev ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: /build
          retention-days: 1

  docker:
    name: Build&Deploy Docker Image
    runs-on: ubuntu-latest
    needs: gradle
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      Lib: $REPO/docker
      APP: 711-community
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve built artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: /build

      - name: Building Docker Image
        run: |
          docker login $REPO -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t $Lib/$APP:${GITHUB_RUN_ID} -t $Lib/$APP:latest .
          docker push $Lib/$APP:${GITHUB_RUN_ID}
          docker push $Lib/$APP:latest