name: Docker Build 🚀

on:
  push:
    branches: [ "feature/**", "master" ]
  workflow_dispatch:

jobs:
  gradle:
    name: Gradle Build
    runs-on: ubuntu-22.04
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      Lib: ${{ secrets.DOCKER_REPO }}/docker
      APP: 711-community
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: make application-hidden.yaml
        run: |
          cd ./src/main/resources
          touch ./application-hidden.yaml
          echo "${{ secrets.hidden }}" >> ./application-hidden.yaml
          
          modified_secret=$(echo "$secret" | sed 's/./&%/g;s/%$//')
          echo "$modified_secret"          

          cat ./application-hidden.yaml
        shell: bash

      - name: Cache Gradle packages
        uses: actions/cache@v2				# Gradle dependency 캐싱 설정(테스트 속도 향상)
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: SPRING_PROFILES_ACTIVE=dev ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Building Docker Image
        run: |
          docker login $REPO -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t $Lib/$APP:${GITHUB_RUN_ID} -t $Lib/$APP:latest .
          docker push $Lib/$APP:${GITHUB_RUN_ID}
          docker push $Lib/$APP:latest