name: Docker Build 🚀

on:
  push:
    branches: [ "feature*", "master" ]
  workflow_dispatch:

jobs:
  gradle:
    name: Gradle Build
    runs-on: ubuntu-22.04
    env:
      APP: coin-community
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ${{ env.APP }}/gradlew

      - name: Test with Gradle
        working-directory: ${{ env.APP }}
        run: SPRING_PROFILES_ACTIVE=dev ./gradlew test

      - name: Build with Gradle
        working-directory: ${{ env.APP }}
        run: ./gradlew build -x test

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ${{ env.APP }}/build
          retention-days: 1

  docker:
    name: Build&Deploy Docker Image
    runs-on: ubuntu-latest
    needs: gradle
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      APP: 711-community
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve built artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: ${{ env.APP }}/build

      - name: Building Docker Image
        working-directory: ${{ env.APP }}
        run: |
          docker login harbor.ha-ving.store -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t harbor.ha-ving.store/docker/$REPO:${GITHUB_RUN_ID} -t $REPO:latest .
          docker push harbor.ha-ving.store/docker/$REPO:${GITHUB_RUN_ID}
          docker push harbor.ha-ving.store/docker/$REPO:latest